project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Avery Sheindlin"
  date: "Date Here"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/activity-01.qmd
      - activities/activity-02.qmd
      - activities/activity-03.qmd
      - activities/03-univariate-viz-notes.qmd
      - activities/Bivariate-viz.qmd
      - activities/Multivariat-viz.qmd
      - activities/Spatial-viz.qmd
      - activities/Effective-viz.qmd
      - activities/Wrangle-Verb.qmd
      - activities/Wrangling-Practice.qmd
      - activities/Reshaping-Data.qmd
      - activities/Joining-Data.qmd
      - activities/Factors.qmd
      - activities/Strings.qmd
    
    - part: notes/README.qmd
      chapters: 
      - notes/note-01.qmd
      - notes/note-02.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: false
  freeze: auto
